[package]
name = "meshql-cert"
version = "0.1.0"
edition = "2021"
description = "meshql-cert — part of the meshql framework"
license = "MIT"
repository = "https://github.com/tailoredshapes/meshql-rs"

[dependencies]
meshql-core = { version = "0.1.0", path = "../meshql-core" }
meshql-server = { version = "0.1.0", path = "../meshql-server" }
meshql-graphlette = { version = "0.1.0", path = "../meshql-graphlette" }
meshql-restlette = { version = "0.1.0", path = "../meshql-restlette" }
cucumber = "0.21"
tokio = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
axum = { workspace = true }
handlebars = { workspace = true }
async-trait = { workspace = true }

[lib]
name = "meshql_cert"
